name: opensfm
dependencies:
  # - python=3.10
  - python=3.12
  - cmake=3.31
  - pip
  - pip:
    - cloudpickle>=0.4.0
    - exifread>=2.1.2
    - flask>=2.3.2
    - fpdf2>=2.4.6
    - joblib>=0.14.1
    - matplotlib
    - networkx>=2.5
    - numpy>=1.19
    # - pillow>=8.1.1
    - pillow==12.1.1
    - pyproj>=1.9.5.1
    - pytest>=3.0.7
    - python-dateutil>=2.7
    - pyyaml>=5.4
    - scipy>=1.10.0
    - sphinx==6.0
    - six
    - xmltodict>=0.10.2
    - wheel
    - opencv-python>=4.5.1.48
